name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          pip install pandas scikit-learn joblib -i https://pypi.tuna.tsinghua.edu.cn/simple

      - name: 训练模型，生成linear_model.txt
        run: |
          python train_model.py

      - name: 配置Git并推送到release分支
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add linear_model.txt
          git commit -m "Auto-update model"
          git push --force origin HEAD:release